version: '3'

services:
  toon_crud_ms:
    container_name: toon_crud_ms
    restart: always
    build: .
    ports:
      - "5000:5000"
    links:
     - toon_crud_db
    volumes:
      - .:/usr/src/app
  toon_crud_db:
    container_name: toon_crud_db
    image: postgres
    logging:
     driver: none

    