version: '3'

services:
  toon_crud_ms:
    container_name: toon_crud_ms
    restart: always
    build: .
    ports:
      - "5005:5000"
    links:
     - toon_crud_db
    volumes:
      - .:/usr/src/app
  toon_crud_db:
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: toonun_usuario
    container_name: toon_crud_db
    image: postgres:13
    logging:
     driver: none

    